### ISSUE TITLE
Cannot build gdlde on Linux

### ISSUE THREAD

**Issue by Csega** [gnudatalanguage/gdlde#2] opened 2018-06-14 13:55 UTC
Hi Folks!

Unfortunately, I could not compile gdlde on Linux. I've installed openjdk8 and run ./gradlew and got the following error message:

"FAILURE: Build failed with an exception.

* Where:
Build file '/home/[user]/gdlde/gdlde/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating project ':gdlde'.
> Could not find property 'eclipseMavenGroup' on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@13803a94.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED"

Can you help me? What did I do wrong? Should I include the full stacktrace/debug info or is it something trivial I overlooked?

**Comment by slayoo** [comment] 2018-06-15 06:39
Thank you @Csega !
@pjb7687 any hints?

**Comment by Csega** [comment] 2018-06-21 11:32
@slayoo, @pjb7687, any news on this?

**Comment by slayoo** [comment] 2018-06-21 11:50
will look into it

**Comment by slayoo** [comment] 2018-06-25 18:44
reproduced on Debian with openjdk8 (for the record, trying with newer jdks failed due to "Could not determine java version from" errors)... TBC

**Comment by slayoo** [comment] 2018-06-25 20:01
Here are the error messages after stripping the traces:
```
Could not resolve all dependencies for configuration ':gdlde:runtime'.
Cause 1: org.gradle.api.internal.artifacts.ivyservice.ModuleVersionNotFoundException: 
  Could not find any version that matches eclipse-luna-sr2:org.eclipse.core.runtime:+.
...
```

**Comment by Csega** [comment] 2018-06-26 12:31
I tried to install the eclipse platform, but is has an openjdk11 dependency, and when I rerun gradlew, it says, that:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

What should we do now?

**Comment by pjb7687** [comment] 2018-06-26 14:35
Hi, I once compiled gdlde on linux only very long time ago, and it has never been tested under recent linux distros. I will have a look in this weekend on my ubuntu machine.

**Comment by slayoo** [comment] 2018-06-26 14:36
@pjb7687 thank you!!!

**Comment by nbjones1** [comment] 2018-06-29 02:05
Also had the exact same problem but on windows 7 Enterprise. Keen to learn if the fix is successful

**Comment by pjb7687** [comment] 2018-07-02 09:12
The error occurs because the gradle plugin (wuff) is simply too old, and it tries to retrieve too old version of eclipse. The problem is nearly all of the repos nowadays do not serve such an old eclipse version anymore.

I discovered that this issue is also recently adressed by other users (https://github.com/akhikhl/wuff/pulls) and I will try suggested solutions there. Otherwise I might use maven tycho (https://www.eclipse.org/tycho/) instead of gradle.

**Comment by Csega** [comment] 2018-07-02 09:36
Hi Guys!

On the weekend I played with it a little, upgraded Gradle to the newest version (4.8), so it recognizes Java 10.0.1 now. But the problem is with wuff, the new system somehow cannot apply the Eclipse app patch. The exact error is:

```
Welcome to Gradle 4.8!

Here are the highlights of this release:
 - Dependency locking
 - Maven Publish and Ivy Publish plugins improved and marked stable
 - Incremental annotation processing enhancements
 - APIs to configure tasks at creation time

For more details see https://docs.gradle.org/4.8/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
Download https://jcenter.bintray.com/org/akhikhl/wuff/wuff-plugin/maven-metadata.xml

FAILURE: Build failed with an exception.

* Where:
Build file '/home/csega/gdlde/gdlde/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':gdlde'.
> Failed to apply plugin [id 'org.akhikhl.wuff.eclipse-ide-app']
   > Cannot cast object '[configuration ':gdlde:publicLib']' with class 'java.util.ArrayList' to class 'org.gradle.api.file.FileCollection' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.file.FileCollection(org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated)
```

Do you have any idea, what is this and how can we solve this issue? I tried to look for this error on the wuff page on github, but couldn't find any applicable solution.

**Comment by Csega** [comment] 2018-07-03 08:46
@pjb7687 Yeah, it seems, that wuff hasn't been upgraded since Sep25, 2015, so it might've been abandoned. Maven tycho seems professional enough to use (and since it's one of Eclipse's own projects, hopefully it won't be abandoned), however, I don't have enough knowledge about Java (or Maven) to use it. I just started to learn Gradle.

**Comment by pjb7687** [comment] 2018-07-03 12:36
@Csega Yes it seems like there is a repo that works with recent Gradle: https://github.com/bueli/wuff

**Comment by Csega** [comment] 2018-07-04 08:36
@pjb7687 I tried to use the new one, but then it does not find unpuzzle. However, I could not find, where to change it. Can you help me with this?

**Comment by nbjones1** [comment] 2018-07-04 10:55
Tried to install the recent Gradle via wuff and got the following error on the second attempt:

c:\temp\wuff-master>gradlew.bat install

FAILURE: Build failed with an exception.

*	Where:
Build  file   · C:\temp\wuff-master\build.gradle·  line:   18

*	What went wrong:
A  problem  occurred  evaluating  root  project  ·wuff-master·.
>  Could  not  get  unknown  property   'developerid'  for  object  of  type org.gradle.ap
.internal.plugins.DefaultExtraPropertiesExtension.

*	Try:	--stacktrace  option  to  get  the  stack  trace.  Run  with  --info  or  --debugI
option to get more  log output. Run  with  --scan to get full  insights.

*	Get more help at https://help.gradle.org BUILD FAILED in ls

**Comment by pjb7687** [comment] 2018-07-04 13:03
@Csega Sorry I didn't mention it; he also released modified unpuzzle (https://github.com/bueli/unpuzzle). You can find his comment here: https://github.com/akhikhl/wuff/issues/119#issuecomment-370580589

**Comment by nbjones1** [comment] 2018-07-04 23:40
Not sure how installing unpuzzle helps the issue with GDL. I successfully installed unpuzzle without errors, but this does not help the GDL install (same errors as before).

**Comment by Csega** [comment] 2018-07-05 17:07
@pjb7687 It is interesting... I got the following error with the new (bue) wuff:

```
csega@DESKTOP-0NB5FRR:~/gdlde$ ./gradlew
Download https://jcenter.bintray.com/bue/akhikhl/wuff/wuff-plugin/maven-metadata.xml
Download https://jcenter.bintray.com/bue/akhikhl/wuff/wuff-plugin/0.0.3/wuff-plugin-0.0.3.pom

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'gdlde'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find bue.akhikhl.unpuzzle:unpuzzle-plugin:0.0.25.
     Searched in the following locations:
       - file:/home/csega/.m2/repository/bue/akhikhl/unpuzzle/unpuzzle-plugin/0.0.25/unpuzzle-plugin-0.0.25.pom
       - file:/home/csega/.m2/repository/bue/akhikhl/unpuzzle/unpuzzle-plugin/0.0.25/unpuzzle-plugin-0.0.25.jar
       - https://jcenter.bintray.com/bue/akhikhl/unpuzzle/unpuzzle-plugin/0.0.25/unpuzzle-plugin-0.0.25.pom
       - https://jcenter.bintray.com/bue/akhikhl/unpuzzle/unpuzzle-plugin/0.0.25/unpuzzle-plugin-0.0.25.jar
     Required by:
         project : > bue.akhikhl.wuff:wuff-plugin:0.0.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

It seems to me, that it tries to download the new unpuzzle, but it does not find it. Indeed, I tried to go to [the website](https://jcenter.bintray.com/bue/akhikhl/unpuzzle/unpuzzle-plugin/0.0.25/), and did not find the .jar file, only a .jar.asc. Should there be a .jar there, or just need to set something pomless (I learnt this expression recently)?

**Comment by pjb7687** [comment] 2018-07-05 20:09
@Csega So I guess you used the new wuff directly from jcenter. Yes I also tried it in the last week, it didn't work since the version number of the new plugins is different - the new wuff is numbered to 0.0.3 and unpuzzle is 0.0.2, but wuff still tries to find unpuzzle 0.0.25.

Since I don't know how to use gradle plugins directly from its source code (well I once tried to use `jitpack` https://github.com/jitpack/jitpack.io - but it doesn't seem to work), I couldn't try the new wuff neither.

**Comment by pjb7687** [comment] 2018-07-05 20:11
@nbjones1 I am not sure neither, but I am just guessing bue's new wuff might already have fixed the issues.

**Comment by nbjones1** [comment] 2018-07-06 01:34
Just tried the new wuff and this time it failed trying to download eclipse luna. The error message is:

Execution failed for task ':libs:unpuzzle:insatllEclipse'.
> java.io.FileNotFoundException: http://mirror.netcologne.de/eclipse//technology/epp/downloads/release/luna/SR2/eclipse-jee-luna-SR2-win32-x86_64.zip

**Comment by texadactyl** [comment] 2018-08-02 15:57
Running Ubuntu 18.04 up-to-date.  Forced to try gradle 4.8.1 with gdlde since the Ubuntu repo version (3.4) fails similarly to what is described above.

Ran `bash gradlew --debug build` and got this result as an attempt to build:
```
10:44:15.533 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Build file '/home/elkins/Downloads/gdlde-master/gdlde/build.gradle' line: 2
A problem occurred evaluating project ':gdlde'.] from daemon DaemonInfo{pid=29687, address=[ef2d6890-6e91-49cc-af6a-5597cf225a45 port:40509, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1533224437477, context=DefaultDaemonContext[uid=62d3ed9e-e9eb-451f-afdc-2c65bd61786f,javaHome=/usr/lib/jvm/java-11-openjdk-amd64,daemonRegistryDir=/home/elkins/.gradle/daemon,pid=29687,idleTimeout=10800000,daemonOpts=-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
10:44:15.534 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
10:44:15.534 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop
```
Full log is attached.
[gradlew.log](https://github.com/gnudatalanguage/gdlde/files/2254159/gradlew.log)

It seems to be complaining about line 2 of this:
```
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }

    dependencies {
        classpath 'org.akhikhl.wuff:wuff-plugin:+'
    }
}

subprojects {
    repositories {
        mavenLocal()
        jcenter()
    }
}
```
That is supplied by the gdlde project.  Some disagreement between gdlde and gradle or did I not set up yet another prerequisite?

**Comment by ShamrockLee** [comment] 2020-10-30 18:43
The problem is relevant on Debian 10 (Buster) with OpenJDK 11.0.9 and Gradle 6.7.
The terminal output
```
Step 17/17 : RUN cd /opt; git clone https://github.com/gnudatalanguage/gdlde; cd /opt/gdlde; gradle build
 ---> Running in 7666acce49e6
Cloning into 'gdlde'...
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/opt/gdlde/gdlde/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':gdlde'.
> Failed to apply plugin 'org.akhikhl.wuff.eclipse-ide-app'.
   > Plugin with id 'osgi' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
The command '/bin/sh -c cd /opt; git clone https://github.com/gnudatalanguage/gdlde; cd /opt/gdlde; gradle build' returned a non-zero code: 1

```
occurs while building this Dockerfile:
```Dockerfile
FROM jlesage/baseimage-gui:debian-10
ENV APP_NAME="GDLDE"
ENV UID=1000
ENV GID=100
RUN \
mkdir /shared_dir && \
ln -s /shared_dir/startapp.sh /startapp.sh
RUN \
apt-get update && \
apt-get install -y apt-utils debconf && \
apt-get upgrade -y && \
apt-get install -y mc tree eterm xfonts-base htop && \
apt-get install -y gnudatalanguage

RUN apt-get install -y curl wget gnupg git

RUN set -eux; \
	apt-get install -y --no-install-recommends \
		bzip2 \
		unzip \
		xz-utils \
		\
# utilities for keeping Debian and OpenJDK CA certificates in sync
		ca-certificates p11-kit \
		\
# java.lang.UnsatisfiedLinkError: /usr/local/openjdk-11/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory
# java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11FontManager
# https://github.com/docker-library/openjdk/pull/235#issuecomment-424466077
		fontconfig libfreetype6 \
	; \
	rm -rf /var/lib/apt/lists/*

# Default to UTF-8 file.encoding
ENV LANG C.UTF-8

ENV JAVA_HOME /usr/local/openjdk-11
ENV PATH $JAVA_HOME/bin:$PATH

# backwards compatibility shim
RUN { echo '#/bin/sh'; echo 'echo "$JAVA_HOME"'; } > /usr/local/bin/docker-java-home && chmod +x /usr/local/bin/docker-java-home && [ "$JAVA_HOME" = "$(docker-java-home)" ]

# https://adoptopenjdk.net/upstream.html
# >
# > What are these binaries?
# >
# > These binaries are built by Red Hat on their infrastructure on behalf of the OpenJDK jdk8u and jdk11u projects. The binaries are created from the unmodified source code at OpenJDK. Although no formal support agreement is provided, please report any bugs you may find to https://bugs.java.com/.
# >
ENV JAVA_VERSION 11.0.9
# https://github.com/docker-library/openjdk/issues/320#issuecomment-494050246
# >
# > I am the OpenJDK 8 and 11 Updates OpenJDK project lead.
# > ...
# > While it is true that the OpenJDK Governing Board has not sanctioned those releases, they (or rather we, since I am a member) didn't sanction Oracle's OpenJDK releases either. As far as I am aware, the lead of an OpenJDK project is entitled to release binary builds, and there is clearly a need for them.
# >

RUN set -eux; \
	\
	arch="$(dpkg --print-architecture)"; \
# this "case" statement is generated via "update.sh"
	case "$arch" in \
# arm64v8
		arm64 | aarch64) downloadUrl=https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.9%2B11/OpenJDK11U-jdk_aarch64_linux_11.0.9_11.tar.gz ;; \
# amd64
		amd64 | i386:x86-64) downloadUrl=https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.9%2B11/OpenJDK11U-jdk_x64_linux_11.0.9_11.tar.gz ;; \
# fallback
		*) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; \
	esac; \
	\
	wget -O openjdk.tgz.asc "$downloadUrl.sign"; \
	wget -O openjdk.tgz "$downloadUrl" --progress=dot:giga; \
	\
	export GNUPGHOME="$(mktemp -d)"; \
# TODO find a good link for users to verify this key is right (https://mail.openjdk.java.net/pipermail/jdk-updates-dev/2019-April/000951.html is one of the only mentions of it I can find); perhaps a note added to https://adoptopenjdk.net/upstream.html would make sense?
# no-self-sigs-only: https://salsa.debian.org/debian/gnupg2/commit/c93ca04a53569916308b369c8b218dad5ae8fe07
	gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options no-self-sigs-only --recv-keys CA5F11C6CE22644D42C6AC4492EF8D39DC13168F; \
# also verify that key was signed by Andrew Haley (the OpenJDK 8 and 11 Updates OpenJDK project lead)
# (https://github.com/docker-library/openjdk/pull/322#discussion_r286839190)
	gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys EAC843EBD3EFDB98CC772FADA5CD6035332FA671; \
	gpg --batch --list-sigs --keyid-format 0xLONG CA5F11C6CE22644D42C6AC4492EF8D39DC13168F \
		| tee /dev/stderr \
		| grep '0xA5CD6035332FA671' \
		| grep 'Andrew Haley'; \
	gpg --batch --verify openjdk.tgz.asc openjdk.tgz; \
	gpgconf --kill all; \
	rm -rf "$GNUPGHOME"; \
	\
	mkdir -p "$JAVA_HOME"; \
	tar --extract \
		--file openjdk.tgz \
		--directory "$JAVA_HOME" \
		--strip-components 1 \
		--no-same-owner \
	; \
	rm openjdk.tgz*; \
	\
# TODO strip "demo" and "man" folders?
	\
# update "cacerts" bundle to use Debian's CA certificates (and make sure it stays up-to-date with changes to Debian's store)
# see https://github.com/docker-library/openjdk/issues/327
#     http://rabexc.org/posts/certificates-not-working-java#comment-4099504075
#     https://salsa.debian.org/java-team/ca-certificates-java/blob/3e51a84e9104823319abeb31f880580e46f45a98/debian/jks-keystore.hook.in
#     https://git.alpinelinux.org/aports/tree/community/java-cacerts/APKBUILD?id=761af65f38b4570093461e6546dcf6b179d2b624#n29
	{ \
		echo '#!/usr/bin/env bash'; \
		echo 'set -Eeuo pipefail'; \
		echo 'if ! [ -d "$JAVA_HOME" ]; then echo >&2 "error: missing JAVA_HOME environment variable"; exit 1; fi'; \
# 8-jdk uses "$JAVA_HOME/jre/lib/security/cacerts" and 8-jre and 11+ uses "$JAVA_HOME/lib/security/cacerts" directly (no "jre" directory)
		echo 'cacertsFile=; for f in "$JAVA_HOME/lib/security/cacerts" "$JAVA_HOME/jre/lib/security/cacerts"; do if [ -e "$f" ]; then cacertsFile="$f"; break; fi; done'; \
		echo 'if [ -z "$cacertsFile" ] || ! [ -f "$cacertsFile" ]; then echo >&2 "error: failed to find cacerts file in $JAVA_HOME"; exit 1; fi'; \
		echo 'trust extract --overwrite --format=java-cacerts --filter=ca-anchors --purpose=server-auth "$cacertsFile"'; \
	} > /etc/ca-certificates/update.d/docker-openjdk; \
	chmod +x /etc/ca-certificates/update.d/docker-openjdk; \
	/etc/ca-certificates/update.d/docker-openjdk; \
	\
# https://github.com/docker-library/openjdk/issues/331#issuecomment-498834472
	find "$JAVA_HOME/lib" -name '*.so' -exec dirname '{}' ';' | sort -u > /etc/ld.so.conf.d/docker-openjdk.conf; \
	ldconfig; \
	\
# basic smoke test
	fileEncoding="$(echo 'System.out.println(System.getProperty("file.encoding"))' | jshell -s -)"; [ "$fileEncoding" = 'UTF-8' ]; rm -rf ~/.java; \
	javac --version; \
	java --version

RUN \
cd /opt; \
mkdir /opt/gradle; \
wget https://services.gradle.org/distributions/gradle-6.7-bin.zip; \
ls; \
unzip -d /opt/gradle ./gradle-6.7-bin.zip; \
ls /opt/gradle/gradle-6.7; \
/opt/gradle/gradle-6.7/bin/gradle -v

ENV PATH $PATH:/opt/gradle/gradle-6.7/bin

RUN \
cd /opt; \
git clone https://github.com/gnudatalanguage/gdlde; \
cd /opt/gdlde; \
gradle build
```

The the installation of Gradle 6.7 is to make it work on Jdk11.(The gradle wrapper in this project comes with Gradle 2, but it requires Gradle 5 to support Jdk11.)

Credit: The jdk installation part in this Dockerfile is borrowed and adapted from [the corresponding Dockerfile](https://github.com/docker-library/openjdk/blob/a1056a406c11909319b95a9631933cdc2035005a/11/jdk/buster/Dockerfile) in the project docker-library/openjdk. This Dockerfile is based on the Debian Buster flavored image in the project [jlesage/docker-baseimage-gui](https://github.com/jlesage/docker-baseimage-gui).

**Comment by slayoo** [comment] 2020-11-01 09:10
Thank you @ShamrockLee! 
Do I understand correctly, that this should be changed:
https://github.com/gnudatalanguage/gdlde/blob/master/gradle/wrapper/gradle-wrapper.properties#L6

Could you help us by creating a PR?

**Comment by ShamrockLee** [comment] 2020-11-01 11:41
@slayoo 
The Gradle wrapper is updated successfully, but the plugin `org.akhikhl.wuff.eclipse-ide-app`is still failed to apply.

**Comment by pjb7687** [comment] 2021-01-01 16:34
Happy new year! Now it should be compilable. I removed the legacy codes, and updated the project to use Maven Tycho instead.

**Comment by pjb7687** [comment] 2021-01-10 21:48
The CI build works, I am closing this now...

**Closed as completed by pjb7687** 2021-01-10 21:48 UTC

**Comment by slayoo** [comment] 2021-01-10 21:54
Thanks!

**Comment by Csega** [comment] 2021-02-18 12:35
Thank you! When I'll have some time, I'll make a few tests with it! Great news! 😄
